import re
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

REPORT_DIR = Path(__file__).resolve().parents[2] / "reports"


def _clean_text(value) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2192": "->",
    }
    for source, replacement in replacements.items():
        text = text.replace(source, replacement)
    return text.encode("latin-1", "replace").decode("latin-1")


def _safe_file_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "_", name.strip()).strip("_")
    return cleaned or "patient"


class HealthReport(FPDF):
    def header(self):
        self.set_fill_color(37, 99, 235)
        self.rect(0, 0, 210, 24, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 12, "Personalized AI Health Assessment", 0, 1, "C")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, "AI-assisted screening report for clinical review", 0, 1, "C")
        self.ln(10)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 116, 139)
        self.multi_cell(
            0,
            4,
            "This report is generated by an AI-assisted risk screening tool and is not a medical diagnosis. "
            "Please review results with a qualified clinician.",
            align="C",
        )


def _section_title(pdf: FPDF, title: str):
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 9, _clean_text(title), 0, 1, "L", True)
    pdf.ln(2)


def _risk_label(probability: float) -> str:
    if probability >= 0.5:
        return "High"
    if probability >= 0.25:
        return "Moderate"
    return "Low"


def generate_pdf_report(data: dict) -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    pdf = HealthReport()
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()

    pdf.set_text_color(15, 23, 42)
    _section_title(pdf, "Patient Data")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, _clean_text(f"Name: {data.get('name', 'Patient')}"), 0, 1)
    pdf.cell(
        0,
        7,
        _clean_text(
            f"Age: {data.get('age', '--')} | Gender: {data.get('gender', '--')} | "
            f"BMI: {data.get('bmi', '--')} | Glucose: {data.get('glucose', '--')} mg/dL"
        ),
        0,
        1,
    )
    pdf.cell(0, 7, _clean_text(f"Blood Pressure Status: {data.get('bp_status', '--')}"), 0, 1)
    pdf.cell(0, 7, _clean_text(f"Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}"), 0, 1)
    pdf.ln(4)

    _section_title(pdf, "Clinical Insight (AI Generated)")
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(0, 7, _clean_text(data.get("ai_recommendation", "No AI summary available.")))
    pdf.ln(4)

    _section_title(pdf, "Diagnostic Risk Scores")
    for key, result in data.get("results", {}).items():
        probability = float(result.get("probability", 0) or 0)
        prob_percent = f"{round(probability * 100)}%"
        risk_label = _risk_label(probability)

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, _clean_text(f"{key.title()} Risk: {prob_percent} ({risk_label})"), 0, 1)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(0, 6, _clean_text(f"Justification: {result.get('justification', 'Not available.')}"))

        top_factors = result.get("top_factors", [])[:3]
        if top_factors:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, "Top contributing factors:", 0, 1)
            pdf.set_font("Helvetica", "", 9)
            for factor in top_factors:
                pdf.cell(
                    0,
                    5,
                    _clean_text(
                        f"- {factor.get('feature', 'Unknown')}: value {factor.get('value', '--')}, "
                        f"influence {round(float(factor.get('influence', 0) or 0), 3)}"
                    ),
                    0,
                    1,
                )
        pdf.ln(3)

    file_name = f"{_safe_file_name(data.get('name', 'patient'))}_health_report.pdf"
    path = REPORT_DIR / file_name
    pdf.output(path)
    return path
